### ISSUE TITLE
Does not work with table

### ISSUE THREAD

**Issue by anoopsinghbayes** [theoinglis/ngAnimate.css#1]
I tried hard to make this work with table, but the effect is not as expected here is the [plunker](http://plnkr.co/edit/8cSIQhJwJJWsDk5J739l?p=preview)

**Comment by theoinglis** [comment]
Unfortunately, and for obvious reasons, tables are very strict on their position and sizing, which means that it is hard to overwrite them. This means animations like collapsing are quite hard to achieve on tables and as such ngAnimate.css doesn't work with tables.
