### ISSUE TITLE
Slide animations are chunky

### ISSUE THREAD

**Issue by brian-slate** [theoinglis/ngAnimate.css#6]
It seems that when doing an ng-show on a hidden element with a nga-slide animation, the entire height of the element is chunked in, and then the slide comes in over the top of existing elements. I see that the warning tooltip indicates I should add padding and max-height, but most times it's not possible for me to know the height (like a hide/show accordion box with arbitrary content length). How should these cases be handled?

**Comment by theoinglis** [comment]
Sorry for the long delay. The reason I used max-height is it means you don't need to know the exact height of the object. As long as the max-height is greater than the greatest possible height it will perform a smooth animation from start to finish.

For animation that doesn't depend on height being set I would need javascript which is something I wasn't intending to add to keep the framework light and easy to use. It might be something I eventually add as an extra optional part though.

Let me know if you have any more questions
