### ISSUE TITLE
Flickering on Remove

### ISSUE THREAD

**Issue by djskinner** [theoinglis/ngAnimate.css#8]
Is there anything I can do to prevent the flickering when clearing items from a repeat?

See example here: http://codepen.io/djskinner/pen/ZYZYYp

**Comment by theoinglis** [comment]
If I understand what you mean by flickering it looks like you are referring to the rows rotating beyond 90 degrees due to perspective. You can either remove the perspective or change the perspective origin? Hopefully that helps.
