### ISSUE TITLE
nga-default necessary ?

### ISSUE THREAD

**Issue by xhuberdeau** [theoinglis/ngAnimate.css#9]
Hi !
I would like to only use slide-left on item remove event in a ng-repeat. However, I don't want any other effect (like the fade which happens when selecting another element in the list of ng-repeat). If i use only the class "nga-slide-left-remove " it doesn't work, but with "nga-default nga-slide-left-remove " it works but i don't want that fade effect.

Do I have to make my own css class that cancel the fade effects or is there an alternative ?

Thank you for this awesome project.

**Comment by theoinglis** [comment]
Sorry for the delay.

Thanks very much for the feedback :). I am glad you are enjoying the project.

There shouldn't be any fade effect with just 'nga-default nga-slide-left-remove'. If you try it out on the [demo site](http://theoinglis.github.io/ngAnimate.css/) (which I am sure you have) there doesn't look like there is any fade effect. Do you have any other classes on that might be causing the fade?
